/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.DichVuBUS;
import BUS.GoiDichVuBUS;
import BUS.LoaiDVBUS;
import BUS.ThuePhongBUS;
import DAO.GoiDichVuDAO;
import DAO.ThuePhongDAO;
import DTO.DichVuDTO;
import DTO.LoaiDVDTO;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Image;
import java.sql.Blob;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Hainguyen
 */
public class GoiDichVuGUI_2 extends javax.swing.JDialog {

    java.awt.Dialog parent;
    DefaultTableModel dtm;

    /**
     * Creates new form GoiDichVuGUI_2
     * @param parent
     * @param modal
     */
    public GoiDichVuGUI_2(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadcbLoaiDV();
    }

    @Override
    public Dialog getParent() {
        return parent;
    }

    public void setParent(Dialog parent) {
        this.parent = parent;
    }

    public void loadcbLoaiDV() {
        ArrayList<LoaiDVDTO> arr = LoaiDVBUS.LoaiDVAll();
        LoaiDVDTO dv;
        cbLoaiDV.removeAllItems();
        for (int i = 0; i < arr.size(); i++) {
            dv = arr.get(i);
            String TenLDV = dv.getTenLDV();
            int MaLDV = dv.getMaLDV();
            cbLoaiDV.addItem(new ComboItem(TenLDV, MaLDV));
        }
    }

    public void loadDichVuAll() {
        String[] header = {"Mã dịch vụ", "Tên dịch vụ", "Đơn giá"};
        dtm = new DefaultTableModel(header, 0);
        ArrayList<DichVuDTO> arr = DichVuBUS.DichVuAll();
        DichVuDTO dv;
//        int rc = dtm.getRowCount();
//        for (int i = 0; i < rc; i++) {
//            dtm.removeRow(0);
//        }
        for (int i = 0; i < arr.size(); i++) {
            dv = arr.get(i);
            int MaDV = dv.getMaDV();
            String TenDV = dv.getTenDV();
            double DonGia = dv.getDonGia();
            Object[] row = {MaDV, TenDV, DonGia};
            dtm.addRow(row);
        }
        tbGoiDV.setModel(dtm);
    }

    public void loadDichVu() {

        ArrayList<DichVuDTO> arr = DichVuBUS.DichVuAll();
        DichVuDTO dv;
        int rc = dtm.getRowCount();
        for (int i = 0; i < rc; i++) {
            dtm.removeRow(0);
        }
        for (int i = 0; i < arr.size(); i++) {
            dv = arr.get(i);
            int MaDV = dv.getMaDV();
            String TenDV = dv.getTenDV();
            double DonGia = dv.getDonGia();
            Object[] row = {MaDV, TenDV, DonGia};
            dtm.addRow(row);
        }
        tbGoiDV.setModel(dtm);
    }

    public void loadDichVu_Loai(int MaLDV) {
        ArrayList<DichVuDTO> arr = DichVuBUS.DichVu_Loai(MaLDV);
        DichVuDTO dv;
        int rc = dtm.getRowCount();
        for (int i = 0; i < rc; i++) {
            dtm.removeRow(0);
        }
        for (int i = 0; i < arr.size(); i++) {
            dv = arr.get(i);
            int MaDV = dv.getMaDV();
            String TenDV = dv.getTenDV();
            double DonGia = dv.getDonGia();
            Object[] row = {MaDV, TenDV, DonGia};
            dtm.addRow(row);
        }
        tbGoiDV.setModel(dtm);
    }

    public ImageIcon ResizeImage(byte[] pic) {
        ImageIcon myImage;

        myImage = new ImageIcon(pic);

        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(lbHinhAnh.getWidth(), lbHinhAnh.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbGoiDV = new javax.swing.JTable();
        cbLoaiDV = new javax.swing.JComboBox<>();
        btThemDV = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbHinhAnh = new javax.swing.JLabel();
        lbTenDV = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfSoLuong = new javax.swing.JTextField();
        lbMaDV = new javax.swing.JLabel();
        btThem = new javax.swing.JButton();
        btThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tìm kiếm dịch vụ");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(192, 219, 235));

        tbGoiDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã DV", "Tên Dịch Vụ", "Đơn Giá"
            }
        ));
        tbGoiDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbGoiDVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbGoiDV);

        cbLoaiDV.setToolTipText("");
        cbLoaiDV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLoaiDVItemStateChanged(evt);
            }
        });

        btThemDV.setText("Thêm dịch vụ");
        btThemDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemDVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cbLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btThemDV, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLoaiDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btThemDV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(192, 219, 235));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        lbHinhAnh.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lbHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbTenDV.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTenDV.setForeground(new java.awt.Color(136, 24, 50));
        lbTenDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTenDV.setText("Tên dịch vụ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Số lượng");

        tfSoLuong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSoLuong.setText("1");
        tfSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSoLuongKeyTyped(evt);
            }
        });

        lbMaDV.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbMaDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMaDV.setText("Mã DV");

        btThem.setText("Thêm");
        btThem.setEnabled(false);
        btThem.setSelected(true);
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btThoat.setText("Thoát");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbMaDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfSoLuong)
                        .addComponent(lbTenDV, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btThem)
                .addGap(33, 33, 33)
                .addComponent(btThoat)
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem)
                    .addComponent(btThoat))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbGoiDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGoiDVMouseClicked
        int is = tbGoiDV.getSelectedRow();
        TableModel model = tbGoiDV.getModel();
        DichVuDTO dv = DichVuBUS.getDichVu(Integer.parseInt(model.getValueAt(is, 0).toString()));
        lbMaDV.setText("" + dv.getMaDV());
        lbTenDV.setText(dv.getTenDV());
        Blob img = dv.getHinhAnh();
        if (img != null) {
            int blobLength;
            byte[] blobAsBytes = null;
            try {
                blobLength = (int) img.length();
                blobAsBytes = img.getBytes(1, blobLength);
            } catch (SQLException ex) {
                Logger.getLogger(DichVuGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            lbHinhAnh.setIcon(ResizeImage(blobAsBytes));
        } else {
            lbHinhAnh.setIcon(null);
        }
        if (lbMaDV.getText() == null) {
            btThem.setEnabled(false);
        } else {
            btThem.setEnabled(true);
        }
    }//GEN-LAST:event_tbGoiDVMouseClicked

    private void cbLoaiDVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLoaiDVItemStateChanged
        loadDichVuAll();
        if (cbLoaiDV.getSelectedItem() != null) {
            Object item = cbLoaiDV.getSelectedItem();
            int LoaiDV = ((ComboItem) item).getValue();
            if (LoaiDV == 1) {
                loadDichVu();
            } else {
                loadDichVu_Loai(LoaiDV);
            }
        }
    }//GEN-LAST:event_cbLoaiDVItemStateChanged

    private void btThemDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemDVActionPerformed
        DichVuGUI_Them them = new DichVuGUI_Them(this, true);
        them.setVisible(true);
        loadDichVuAll();
        loadcbLoaiDV();
    }//GEN-LAST:event_btThemDVActionPerformed

    private void tfSoLuongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSoLuongKeyTyped
        if (tfSoLuong.getText().length() >= 4) {
            evt.consume();
        }
    }//GEN-LAST:event_tfSoLuongKeyTyped

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        if (GoiDichVuBUS.checkSoLuong(tfSoLuong)) {
            QuanLyDatTiecGUI mhc = (QuanLyDatTiecGUI) this.getParent();
            int MaGDV = GoiDichVuBUS.getSoGoiDV() + 1;
            int MaDV = Integer.parseInt(lbMaDV.getText());
            int SL = Integer.parseInt(tfSoLuong.getText());
            GoiDichVuDAO gdv = new GoiDichVuDAO();
            boolean chk = gdv.InsertGoiDV(MaGDV, mhc.getMaTP(), MaDV, SL);
            if (chk == true) {
                ThuePhongDAO tp = new ThuePhongDAO();
                double TienTraTruoc = ThuePhongBUS.getTienTraTruoc(mhc.getMaTP());
                tp.UpdateTienTraTruoc(mhc.getMaTP(), TienTraTruoc);
                mhc.loadtbDichVu(mhc.getMaTP());
                JOptionPane.showMessageDialog(this, DichVuBUS.getDichVu(MaDV).getTenDV() + ":   " + SL);
            } else {

            }
        } else {
            JOptionPane.showMessageDialog(null, "Số lượng là số tự nhiên lớn hơn 0!");
        }
    }//GEN-LAST:event_btThemActionPerformed

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GoiDichVuGUI_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GoiDichVuGUI_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GoiDichVuGUI_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GoiDichVuGUI_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GoiDichVuGUI_2 dialog = new GoiDichVuGUI_2(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btThem;
    private javax.swing.JButton btThemDV;
    private javax.swing.JButton btThoat;
    private javax.swing.JComboBox<ComboItem> cbLoaiDV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbHinhAnh;
    private javax.swing.JLabel lbMaDV;
    private javax.swing.JLabel lbTenDV;
    private javax.swing.JTable tbGoiDV;
    private javax.swing.JTextField tfSoLuong;
    // End of variables declaration//GEN-END:variables
}
