/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.HoaDonBUS;
import BUS.KhachHangBUS;
import BUS.ThuePhongBUS;
import DAO.MysqlDataAccessHelper;
import DTO.HoaDonDTO;
import java.io.InputStream;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Hainguyen
 */
public class ThongKeGUI extends javax.swing.JFrame {

    DefaultTableModel dtm;
    int MaNV;

    private ThongKeGUI() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setMaNV(int MaNV) {
        this.MaNV = MaNV;
    }

    public int getMaNV() {
        return MaNV;
    }

    /**
     * Creates new form ThongKeGUI
     *
     * @param MaNV
     */
    public ThongKeGUI(int MaNV) {
        initComponents();
        dcbatdau.setDate(new Date());
        dcketthuc.setDate(new Date());
        this.setMaNV(MaNV);
        loadThongKeNgayHT(new Timestamp(new Date().getTime()));
    }

    public void loadThongKeNgay(Date NgayHD) {
        ArrayList<HoaDonDTO> arr = HoaDonBUS.getHoaDon(NgayHD);
        HoaDonDTO kh;
        int rc = dtm.getRowCount();
        for (int i = 0; i < rc; i++) {
            dtm.removeRow(0);
        }
        for (int i = 0; i < arr.size(); i++) {
            kh = arr.get(i);
            int MaHD = kh.getMaHD();
            double TienGio = kh.getTienGio();
            double TienDV = kh.getTienDichVu();
            int GiamGia = kh.getGiamGia();
            double TongTien = kh.getTongTien();
            Object[] row = {MaHD, TienGio, TienDV, GiamGia, TongTien};
            dtm.addRow(row);
        }
        tbThongKeNgay.setModel(dtm);
    }

    public void loadThongKeNgayHT(Date NgayHD) {
        System.out.println("" + NgayHD);
        String[] header = {"Mã hóa đơn", "Tiền giờ", "Tiền dịch vụ", "Giảm giá", "Tổng tiền"};
        dtm = new DefaultTableModel(header, 0);
        ArrayList<HoaDonDTO> arr = HoaDonBUS.getHoaDon(NgayHD);
        HoaDonDTO kh;
        for (int i = 0; i < arr.size(); i++) {
            kh = arr.get(i);
            int MaHD = kh.getMaHD();
            double TienGio = kh.getTienGio();
            double TienDV = kh.getTienDichVu();
            int GiamGia = kh.getGiamGia();
            double TongTien = kh.getTongTien();
            Object[] row = {MaHD, TienGio, TienDV, GiamGia, TongTien};
            dtm.addRow(row);
        }
        tbThongKeNgay.setModel(dtm);
    }

    public void loadHoaDon(Timestamp start, Timestamp end) {
        ArrayList<HoaDonDTO> arr = HoaDonBUS.getHoaDon(start, end);
        HoaDonDTO kh;
        int rc = dtm.getRowCount();
        for (int i = 0; i < rc; i++) {
            dtm.removeRow(0);
        }
        for (int i = 0; i < arr.size(); i++) {
            kh = arr.get(i);
            int MaHD = kh.getMaHD();
            double TienGio = kh.getTienGio();
            double TienDV = kh.getTienDichVu();
            int GiamGia = kh.getGiamGia();
            double TongTien = kh.getTongTien();
            Object[] row = {MaHD, TienGio, TienDV, GiamGia, TongTien};
            dtm.addRow(row);
        }
        tbThongKeNgay.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbThongKeNgay = new javax.swing.JTable();
        btTim = new javax.swing.JButton();
        btInThongKeNgay = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cbThang = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btInThongKeThang = new javax.swing.JButton();
        tfNam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dcbatdau = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        dcketthuc = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thống kê doanh thu");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tbThongKeNgay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbThongKeNgay);

        btTim.setText("Tìm");
        btTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimActionPerformed(evt);
            }
        });

        btInThongKeNgay.setText("In thống kê");
        btInThongKeNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInThongKeNgayActionPerformed(evt);
            }
        });

        cbThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tháng");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Năm");

        btInThongKeThang.setText("In thống kê");
        btInThongKeThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInThongKeThangActionPerformed(evt);
            }
        });

        tfNam.setText("2017");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Doanh thu theo tháng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNam, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btInThongKeThang)))
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(tfNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btInThongKeThang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dcbatdau.setDateFormatString("yyyy-MM-dd");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Doanh thu theo ngày");

        dcketthuc.setDateFormatString("yyyy-MM-dd");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(dcbatdau, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btTim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btInThongKeNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btTim)
                                        .addComponent(btInThongKeNgay))
                                    .addComponent(dcbatdau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dcketthuc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimActionPerformed
        if (HoaDonBUS.checkNgay(dcbatdau)) {
            if (HoaDonBUS.checkNgay(dcketthuc)) {
                Date start = dcbatdau.getDate();
                Date end = dcketthuc.getDate();
                end.setHours(23);
                end.setMinutes(59);
                end.setSeconds(59);
                start.setHours(0);
                start.setMinutes(0);
                start.setSeconds(0);
                Timestamp batdau = new Timestamp(start.getTime());
                Timestamp ketthuc = new Timestamp(end.getTime());
                loadHoaDon(batdau, ketthuc);
            } else {
                JOptionPane.showMessageDialog(null, "error");
                dcketthuc.requestFocusInWindow();
            }
        } else {
            JOptionPane.showMessageDialog(null, "error");
            dcbatdau.requestFocusInWindow();
        }
    }//GEN-LAST:event_btTimActionPerformed

    private void btInThongKeNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInThongKeNgayActionPerformed
        MysqlDataAccessHelper my = new MysqlDataAccessHelper();
        Date start = dcbatdau.getDate();
        Date end = dcketthuc.getDate();
        end.setHours(23);
        end.setMinutes(59);
        end.setSeconds(59);
        start.setHours(0);
        start.setMinutes(0);
        start.setSeconds(0);
        Timestamp batdau = new Timestamp(start.getTime());
        Timestamp ketthuc = new Timestamp(end.getTime());
        try {
            my.open();
            String sql = "select *\n"
                    + " from hoadon\n"
                    + " where NgayHD >= $P{NgayBatDau} and NgayHD <= $P{NgayKetThuc}";
            HashMap<String, Object> map = new HashMap<>();
            map.put("NgayBatDau", batdau);
            map.put("NgayKetThuc", ketthuc);
            InputStream is = getClass().getResourceAsStream("report2.jrxml");

            JRDesignQuery jrDesignQuery = new JRDesignQuery();
            jrDesignQuery.setText(sql);

            JasperDesign jasperDesign = JRXmlLoader.load(is);
            jasperDesign.setQuery(jrDesignQuery);

            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, map, my.getConn());
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException e) {
        }
    }//GEN-LAST:event_btInThongKeNgayActionPerformed

    private void btInThongKeThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInThongKeThangActionPerformed
        MysqlDataAccessHelper my = new MysqlDataAccessHelper();
        int month = cbThang.getSelectedIndex() + 1;
        int year = Integer.parseInt(tfNam.getText());
        try {
            my.open();
            String sql = "select sum(TongTien) as TT, day(NgayHD), month(NgayHD)\n"
                    + "from hoadon \n"
                    + "where month(NgayHD) = " + month + " and year(NgayHD) = " + year + "\n"
                    + "group by date(NgayHD)";
            Map parametersMap = new HashMap();
            InputStream is = getClass().getResourceAsStream("report1.jrxml");

            JRDesignQuery jrDesignQuery = new JRDesignQuery();
            jrDesignQuery.setText(sql);

            JasperDesign jasperDesign = JRXmlLoader.load(is);
            jasperDesign.setQuery(jrDesignQuery);

            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametersMap, my.getConn());
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException e) {
        }
    }//GEN-LAST:event_btInThongKeThangActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new ManHinhChinh(this.getMaNV()).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInThongKeNgay;
    private javax.swing.JButton btInThongKeThang;
    private javax.swing.JButton btTim;
    private javax.swing.JComboBox<String> cbThang;
    private com.toedter.calendar.JDateChooser dcbatdau;
    private com.toedter.calendar.JDateChooser dcketthuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbThongKeNgay;
    private javax.swing.JTextField tfNam;
    // End of variables declaration//GEN-END:variables
}
